/* 🎯HIgh-Level Language ( source code )
            The program which we write using any programming language like c, c++, java, javascript etc.
            is called high level programming language, because it is readable and understandable by human.
    
    🎯Machine Code
            But computer processor does not understand high-level language, It only understand 0's and 1's
            So in order to get it executed on processor, source code need to be converted into 0's and 1's.
            This converted code is called 'machine code'.  ( we cant see machine code directly )
            
            ** This conversion is happen either by 'Compilation process' or 'Interpretation process',
                But modern js, use mixed of both called [ 'just-in-time' ] compilation.

    🎯Compilation process( compiler is used )
            Entire source code get converted into machine code once and stored on separated file.
            And then this file get executed any time.

                in java
                    Hello.java =>   source code.
                    Hello.class =>  byte code. generated by javac ( compile time ). platform-independant
                    and then jvm convert .class file into machine code at runtime.

    🎯Interpretaion process( Interpreter is use )
            Source code get converted into machine code line by line and get executed.
            first line converted and executed, then comes to second line.

    🎯Just-In-Time compilation(modern js)
            Entire source code converted into machine code once but not store on separate file
            it get executed immediately.
    
    
*/


// ---------------------------------------------------------------------------------------------------------


/*  🎯Process and Thread

        Process
                is running instance of your program. 
                When you run program Operating system create process.
                    👉Allocates memory on RAM
                    👉Load program code on RAM.                  
                        eg. when you open chrome. It becomes process.
        
        Thread  
                is smallest unit of execution withing process.
                    👉Every process has atleast 1 main thread 
                    👉can also have multiple worker threads and background threads.
                    👉Threads share memory.
        
        CPU(processor)
                    👉processor gets instruction from RAM
                    👉processor has cores where threads get executed
                    👉OS decides which thread runs where
                    👉one cpu core execute one thread at a time.

                    
                    Learn Time-Slicing and Context-Switching Operating System Concept.

*/


// ---------------------------------------------------------------------------------------------------------

/* 🎯Javascript
        javascript is programming language. It has syntax and rules.
        But by itself alone, It can not be run or execute.
        It needs Runtime Environment.

    Runtime Environment
        Runtime environment is a system which execute javascript code,
        and provide all the necessory resources to execute the code.
        
        👉On Client-Side 'Browser' is Runtime Environment.
        👉On Server-Side 'nodejs' is Runtime Environment.
*/


// ---------------------------------------------------------------------------------------------------------

/* 🎯Javscript is synchronous, dynamically typed, single-threaded programming language.

        🔵synchronous 
            code execute line-by-line, 
            next line can not be executed untill the current line finishes its execution.


        🔵Dynamically typed language  vs Statically typed language


            1️⃣ 
                👉In Dynamic type language ( javascript ) only value has type. variable has no type. 
                    variable can hold value of any data type. 

                        let a = "sandesh"       // a hold string
                        a = 19                  // a become number type, variable can also change its type dynamically.

                👉In Static type language ( java ) variable and value both have type. 
                    variable can not hold value of any data type. 
            
                        int num = 20;
                        num = 'twenty'  // error

            2️⃣  
                👉A dynamically typed language variable types decided at runtime. ( javascript )

                👉A statically typed language variable types decided at compile time. ( Java )


        🔵Single Threaded
                ❗   Every Browser has got something called js engine( computer program ).
                    which executed js code using [ call stack ]. on single main thread 
                    Thats why js called single threaded language.

            Engines like V8 may use multiple threads for:
                    Garbage collection
                    JIT compilation
                    Optimization

            ❗ BUT:
            👉 These threads do NOT execute your JS code directly

            ❗If that single thread is block everything is block,
            That single thread also responsible for creating DOM, CSSOM.

        
        But To achieve asynchronization Browser provide resources like,
            👉Web Api ( timers, fetch, DOM API, console ) they runs on different threads.
            👉Callback Queue( callback functions => function from timers, eventListners waiting for their execution )
            👉MicroTask Queue (Promise, fetch (.then, .catch) waiting for their execution ) 
            👉Event loop (pulls functions from these queues and push to Call Stack when call stack is empty)
                * microtask queue has higher priority. which get executed before callback queue

        
        🔵run and execution.
        
            setTimeout(()=>{
            },1000)

            setTimeout(, 1000)     => timing  runs in background ( web api )

            ()=>{}                 => waiting for their execution in callback queue.
        
            
--------------------------------------------------------------------------
        
        🔁Js Engine (separate embedded program) in browser.

        🔁js Engine has got.

            🎯Stack( Call Stack ) -     👉primitive type stores in stack memory. and where actual js code get exexcuted.

            🎯Heap memory -             👉reference type (array, object, function as an object) stores in Heap memory.
                                            with their refernece(memory address) kept in stack 

                                        👉It's unstructured memory pool which grows dynamically.      


            🔹let a = 19;     
                👉a → stored directly in stack

            🔹let obj = { name: "sandesh" };
                👉obj → is reference( memory address like 0x123 ) stores in stack
                👉the actual object { name: "sandesh" } → stores in heap

            🔹function greet() {
                console.log("Hello");
            }
                👉greet(reference)  -> stores in stack    
                👉function() { console.log("Hello") }  -> stores in  Heap

                👉when call greet()  => function execution context created to executed that function

------------------------------------------------------------------------

            🔹Execution Context ( EC ) :

                Execution Context is the environment where javascript code is executed.
                It is inside call stack.

                🔹Types: 

                    1. Global Execution Context ( GEC )

                            When js file runs first time, js Engine create Global Execution context.
                            GEC is pushed first into Call Stack, It stays there until program ends.
                            There is only one GEC.
                            This is the default environment where your code begins execution.

                    2. Functional Execution Context ( FEC )

                            Every time function is called new function execution context is created for that function on top of GEC.
                            After the function finishes execution, its Execution Context is removed (popped) from the Call Stack.

                                🎯Before execution ends:
                                    [ Function EC ]
                                           |
                                     [ Global EC ]

                                🎯After function completes:
                                    [ Global EC ]

                    
                🔹Phases of Execution Context

                    1. Declaration phase( memory creation phase ) :

                            js scan your code and setup memory, during this phase :
                                👉variable are declared.
                                👉functions are stored in memory.

                                    👉 If variable is declared with var only
                                        Then only it is assigned value undefined.
                                        But not for let and const, they are assigned value in execution phase.
                                            **learn what is Hoisting and TDZ.
                                    👉 Hoisting happens because of memory creation phase.
                                    

                    
                    2. Execution phase ( Initialization phase ) :

                            js engine run code line by line.
                                👉values are assigned.
                                👉expressions are evaluted.

                                    👉variable with var keyword replace with provided value.

        
*/


// ---------------------------------------------------------------------------------------------------------


/*  🎯javascript code Execution
            As we run js code. js engine comes in picture.

                1.  It parse (read) code. not get executed.
                    if error occurs stop parsing and throw error.

                2.  if no error, it produces (AST) abastact syntax tree. It's tree like structure.

                3.  Just-in-time compiler get AST and generate machine code.

                4.  and this machine code get executed by js engine on call stack .

                5.  we not done yet. 
                        To get execute as soon as possible,
                        In the beginning js engine do not create fully-optimize version of machine code,

                        But in the background ( during already running program execution ) 
                        This machine code get optimize and recompile again and again  
                        where un-optimize code swap with optimized code.
                         

                        🎯This process makes, modern js engine like V8 so fast.
                        
*/

// ----------------------------------------------------------------------------------------------------------------

