/*  HIgh-Level Language ( source code )
            The program which we write using any programming language like c, c++, java, javascript etc.
            is called high level programming language, because it is readable and understandable by human.
    
    🎯Machine Code
            But computer processor does not understand high-level language, It only understand 0's and 1's
            So in order to get it executed on processor, source code need to be converted into 0's and 1's.
            This converted code is called 'machine code'.  ( we cant see machine code directly )
            
            ** This conversion is happen either by 'Compilation process' or 'Interpretation process',
                But modern js, use mixed of both called [ 'just-in-time' ] compilation.

    🎯Compilation process( compiler is used )
            Entire source code get converted into machine code once and stored on separated file.
            And then this file get executed any time.

                in java
                    Hello.java =>   source code.
                    Hello.class =>  byte code. generated by javac ( compile time ). platform-independant
                    and then jvm convert .class file into machine code at runtime.

    🎯Interpretaion process( Interpreter is use )
            Source code get converted into machine code line by line and get executed.
            first line converted and executed, then comes to second line.

    🎯Just-In-Time compilation(modern js)
            Entire source code converted into machine code once but not store on separate file
            it get executed immediately.
    
    
*/

// ---------------------------------------------------------

/*  Process and Thread

        Process
                is running instance of your program. 
                When you run program Operating system create process.
                    👉Allocates memory on RAM
                    👉Load program code on RAM.                  
                        eg. when you open chrome. It becomes process.
        
        Thread  
                is smallest unit of execution withing process.
                    👉Every process has atleast 1 main thread 
                    👉can also have multiple worker threads and background threads.
                    👉Threads share memory.
        
        CPU(processor)
                    👉processor gets instruction from RAM
                    👉processor has cores where threads get executed
                    👉OS decides which thread runs where
                    👉one cpu core execute one thread at a time.

                    
                    Learn Time-Slicing and Context-Switching Operating System Concept.

*/

// ---------------------------------------------------------

/*  JS Runtime Environment

        Javascript has syntax and rules.
        But by itself alone, It can not be run or execute.
        It needs Runtime Environment.

        Runtime Environment
            Runtime environment is a system.
            which provides all necessay components in order to use and run js program.
        
            On Client-Side 'Browser' is Runtime Environment.

            On Server-Side 'Node.js' is Runtime Environment.

    However basic structure of Runtime Environment remain same.
*/

// ---------------------------------------------------------

/* Js Engine, Call Stack, Execution Context.

    Javascript Engine:
   
        The Heart of any runtime is JS Engine.
        JS Engine is a simple computer program which executes js code.


        JS Engine will always have:
            1. stack
            2. heap

            Stack and Heap are two conceptual areas used for managing memory and execution.

                👉Primitive data types ared stored in Stack.

                    let name = "sandesh"

                    name = "sandesh"   →     stored on stack.

                👉Objects (other than primitive) are stored in Heap,
                    and variable holding an object, a reference is stored in stack.

                    Heap is used for dynamic allocation of memory it grows and shrink as needes.
                    for eg. as we add element in array it grows...

                    let user = {
                        name: "Sandesh",
                    };

                    user                → stores in stack
                    { name: "sandesh" } → stores in heap

                    // ----------------------------------

                    function greet() {
                        console.log("Hello");
                    }

                    greet(reference)  -> stores in stack 

                    function() { console.log("Hello") }  -> stores in  Heap

                    // ----------------------------------




    Call Stack:
        
        Call Stack keep track of currently execution function.

    // ----------------------------------

    Execution Context (EC):

        Execution Context is an environment where javascript code is executed.
        It is inside Call Stack.

        🔹Types of Execution Context. 

            1. Global Execution Context ( GEC )

                When js file runs first time, js Engine create Global Execution context.
                GEC is pushed first into Call Stack, and remain there until program ends.
            
            2. Functional Execution Context ( FEC )

                Every time function is called new function execution context is created for that function on top of GEC.
                After the function finishes execution, its Execution Context is removed (popped) from the Call Stack.


                    
        🔹Phases of Execution Context

            1. Declaration phase( memory creation phase ) :

                js scan your code and setup memory, during this phase :
                    variable are declared.
                    functions are stored in memory.

                            variable is declared with var keyword assigned "undefined" value.
                            variable declared with let and const, assigned value in execution phase.
                                         
                            learn what is Hoisting and TDZ.
                            Hoisting happens because of memory creation phase.
                                    

            2. Execution phase ( Initialization phase ) :

                    js engine run code line by line.
                        👉values are assigned.
                        👉expressions are evaluted.

                            👉variable with var keyword replace with provided value.

*/

// ---------------------------------------------------------

/*  Js Runtime in case of browser has four main component:

        1.  JS Engine
        2.  Web API ( DOM, Timer, fetch, console.log() )
        3.  Callback Queue and Microtask Queue
        4.  Event Loop.

    
    2. Web API's:

        Browser provides web api's such as Dom api, fetch api, timer functions, console.log() function. 
        It provides extra functionality to js engine, which is not part of js language itself.
        js simply get access to these api's through global window object.


    3. Callback Queue and Microtask Queue

        they are data structures that stores, callback functions of events and promises.

            callback function of events and timers function wait for their execution in  callback queue.
            callback function of promise wait for their execution in microtask queue.

            microtask queue has higher priority than callback queue.


    4. Event loop

        Event loop co-ordinate with Call Stack and these Callback and Microtask Queue.
        Event loop continuosly monitor main therad and 
        once it is empty it pushes these callback function to Call Stack to get it executed.


*/

// ---------------------------------------------------------------------------------------------------------

/* javascript code Execution
            As we run js code. js engine comes in picture.

                1.  It parse (read) code. not get executed.
                    if error occurs stop parsing and throw error.

                2.  if no error, it produces (AST) abastact syntax tree. It's tree like structure.

                3.  Just-in-time compiler get AST and generate machine code.

                4.  and this machine code get executed by js engine using single main theread on call stack .

                5.  we not done yet. 
                        To get execute as soon as possible,
                        In the beginning js engine do not create fully-optimize version of machine code,

                        But in the background ( during already running program execution ) 
                        This machine code get optimize and recompile again and again  
                        where un-optimize code swap with optimized code.
                         

                        🎯This process makes, modern js engine like V8 so fast.
                        
*/

// ----------------------------------------------------------------------------------------------------------------
