/* 🧠   How Browser Paints Everything...

    🔹When you open a website, Browser follows pipeline...

        1. Read HTML → Converts it into a DOM tree (Document Object Model)
                        (Tree structure in memory )

        2. Read CSS → Build CSSOM

        3. Combine → DOM + CSSOM = Render Tree.
                Only visible elements included (e.g. display: none excluded)

        4. Layout (Reflow)
                Browser calculates:
                    position
                    size of elements,
                    spacing

                👉 "Where should this element appear?"
            
        5. Paint
            Browser draws pixels on screen ( colors, borders, text, shadows etc. )

*/

// --------------------------------------------------------------

/* 🧠 What Happens When You Open a React App First Time?

        1. browser receive, index.html file,
           This file contains empty div and reference of javascript file
        
                🔹index.html

                <div id="root"></div>
                <script src="main.js"></script>


        👉Browser 
                Parse(read) HTML → create DOM ( Real Dom )
                parse css - create CSSOM
                Combine → DOM + CSSOM = Render Tree
                Layout calculate
                Paints

            👉 But screen is basically blank
                    because we have empty div 
                    <div id="root"></div>

        
        2.  Now browser download and execute main.jsx

             the javascript bundle file generated by tools like vite or webpack
             and that bundle contains

                        React
                        ReactDOM
                        Your components code (App, and all childs.)

               ReactDOM.createRoot(document.getElementById("root")).render(
                <App />
               );

                 React takes control and start execution...


                🔹  React calls your components (App, children)
                    👉Builds Virtual DOM (JS object)

        3.  ReactDOM Updates Real DOM

             React compares the Virtual DOM structure and converts it into actual browser DOM nodes.
             internally it uses browser api like
             document.createElement() and appendChild()
        
            Then react mount these node into <idv id='root'>

        4.  Now, Browser sees DOM changes
                👉 It runs again:
                        Layout (Reflow)
                        Paint
                    ✅ Now UI becomes visible



        🎯 Important Insight

        👉 First paint in React happens in 2 phases:
            Thats Why React Feels Slightly Slower Initially?

                1. Initial because of Empty div

                2.  After JS executes, React injects DOM → repaint 

        
        🎯  This is called:
                👉 CSR (Client Side Rendering)

*/

// ------------------------------------------------------
